# Generated by Django 5.2 on 2025-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_age_alter_member_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
