# Generated by Django 5.2 on 2025-06-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_email'),
    ]

    operations = [
    ]
