# Generated by Django 5.2 on 2025-06-25 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
    ]
